ins_fetch_entity/Models/TBLEmployee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ins_fetch_entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEmployee
    {
        public int id_pk { get; set; }
        public Nullable<int> employeeId { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
    }
}

ins_fetch_entity/Models/TBLemployee.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ins_fetch_entity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEmployeeEntities : DbContext
    {
        public DBEmployeeEntities()
            : base("name=DBEmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLEmployee> TBLEmployees { get; set; }
    }
}

ins_fetch_entity/Models/TBLemployee.Designer.cs
// T4 code generation is enabled for model 'C:\Users\BIRJU\source\repos\ins_fetch_entity\ins_fetch_entity\Models\TBLemployee.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

ins_fetch_entity/Controllers/employeeController.cs
using ins_fetch_entity.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ins_fetch_entity.Controllers
{
    public class employeeController : Controller
    {
        DBEmployeeEntities context = new DBEmployeeEntities();

        [HttpGet]
        public ActionResult GetAllEmployees()
        {
            List<TBLEmployee> employees = context.TBLEmployees.ToList();
            return View("ShowEmp", employees);
        }

        public ActionResult InsertPage()
            {
                return View("insert");
            }

        [HttpPost]
        public ActionResult InsertData(TBLEmployee e)
        {
            context.TBLEmployees.Add(e);
            context.SaveChanges();
            return RedirectToAction("GetAllEmployees");
        }

        public ActionResult deleterecord(string delete)
        {
            SqlConnection con = new SqlConnection();
            con.ConnectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\BIRJU\source\repos\ins_fetch_entity\ins_fetch_entity\App_Data\DBEmployee.mdf;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30;Application Name=EntityFramework";
            SqlCommand command = new SqlCommand();
            string d = delete;
            command.CommandText = $"DELETE FROM TBLEmployee WHERE name='{d}'";
            command.Connection = con;
            con.Open();
            command.ExecuteNonQuery();
            con.Close();
            

            return RedirectToAction("GetALLEmployees");
        }
    }
}

ins_fetch_entity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ins_fetch_entity/Views/employee/ShowEmp.cshtml
@using ins_fetch_entity.Models
@model List<TBLEmployee>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowEmp</title>
</head>
<body>
    <div class="table-responsive"> 
        <table class="table" border="1">
            <tr>
                    <td>Employee_ID</td>
                    <td>Name</td>
                    <td>City</td>
                    <td>BOD</td>
            </tr>

            @foreach(TBLEmployee a in Model)
            {
                <tr>
                    <th>@a.employeeId</th>
                    <th>@a.name</th>
                    <th>@a.city</th>
                    <th>@a.dateofbirth</th>
                </tr>
            }
        </table>
        @using(Html.BeginForm("deleterecord","employee",FormMethod.Post))
            {
                <input type="text" placeholder="delete" name="delete"/>
                <input type="submit" placeholder="Delete Record"/>
            }

    </div>
</body>
</html>

ins_fetch_entity/Views/employee/insert.cshtml
@using ins_fetch_entity.Models
@model TBLEmployee
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>insert</title>
</head>
<body>

    <section class="h-100 h-custom" >
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <div class="card-body p-4 p-md-5" >
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2" style="background-color:red; display:inline-block">Registration Info</h3><br />
                            <div class="px-md-2">
                                <div class="row">
                                    <div class="col-md-6 mb-4">

                                        <div class="form-outline datepicker">

                                            @using (Html.BeginForm("InsertData", "employee", FormMethod.Post))
                                            {
                                                <div class="form-outline mb-4">
                                                    @Html.TextBoxFor(a => a.employeeId)
                                                    <label>ID</label>
                                                </div>
                                                @Html.TextBoxFor(a => a.name)
                                                <label>name</label>
                                                @Html.TextBoxFor(a => a.city)
                                                <label>city</label><br />
                                                <div style="display:inline-block">
                                                @Html.TextBoxFor(a => a.dateofbirth, "{0:MM/dd/yyyy}", new { @class = "form-control date", type = "date" })
                                                </div>
                                                <div style="display:inline-block">
                                                <input type="submit" class="btn btn-success btn-lg mb-1" />
                                                </div>
                                            }
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                            </div>
                    </div>
                </div>
        
</section>
</body>
</html>